[package]
name = "udpstream"
version = "0.0.0-alpha.1"
authors = ["SajjadPourali <sajjad@securation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha"
tokio-openssl = "0.4.0-alpha"
openssl = "0.10"